permalink: /:year-:month-:day-:title/

baseurl: "/styles/"

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      name: "KlokanTech Styles"
      description: The company web style guide
      baseurl: http://klokantech.github.io/styles