permalink: /:year-:month-:day-:title/

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      name: "KlokanTech Styles"
      description: The company web style guide
