# Name of your site (displayed in the header)
name: KlokanTech Styles

# Short description (displayed in the header)
description: The company web style guide

permalink: pretty

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"

baseurl: "/styles"