# Name of your site (displayed in the header)
name: KlokanTech Styles

# Short description (displayed in the header)
description: The company web style guide

permalink: pretty

sass:
  style: :compressed

baseurl: "http://klokantech.github.io/styles"
