permalink: /:year-:month-:day-:title/

sass:
  style: :compressed
  sass_dir: 'twbs/scss/'

exclude:
  - 'twbs/site'
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      name: "KlokanTech Styles"
      description: The company web style guide
